[pytest]
addopts = -v -s --html=reports/report.html --self-contained-html
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
markers =
    regression: Marks tests as part of the regression suite.
    smoke: Marks tests as part of the smoke suite.
    details: Marks tests as part of details suite
    api: Marks tests as part of api suite
test_id_attribute = data-test